### ISSUE TITLE
支付回调处理时 NoSuchMethodError

### ISSUE THREAD

**Issue by xiangzhanyou** [wechatpay-apiv3/wechatpay-apache-httpclient#127]
![image](https://user-images.githubusercontent.com/18008592/160770133-ebfa1d45-8da6-4967-91c1-47e95a2131e2.png)

.NoSuchMethodError: com.fasterxml.jackson.databind.ObjectReader.readValue(Ljava/lang/String;Ljava/lang/Class;)Ljava/lang/Object;] with root cause

java.lang.NoSuchMethodError: com.fasterxml.jackson.databind.ObjectReader.readValue(Ljava/lang/String;Ljava/lang/Class;)Ljava/lang/Object;

**Comment by lianup** [comment]
可以参考[如何解决Jackson兼容性问题](https://github.com/wechatpay-apiv3/wechatpay-apache-httpclient#如何解决Jackson兼容性问题)。

**Comment by xiangzhanyou** [comment]
> 可以参考[如何解决Jackson兼容性问题](https://github.com/wechatpay-apiv3/wechatpay-apache-httpclient#%E5%A6%82%E4%BD%95%E8%A7%A3%E5%86%B3Jackson%E5%85%BC%E5%AE%B9%E6%80%A7%E9%97%AE%E9%A2%98)。

刚回翻了下，看到了原有的类似问题，谢谢您

**Comment by lianup** [comment]
> > 可以参考[如何解决Jackson兼容性问题](https://github.com/wechatpay-apiv3/wechatpay-apache-httpclient#%E5%A6%82%E4%BD%95%E8%A7%A3%E5%86%B3Jackson%E5%85%BC%E5%AE%B9%E6%80%A7%E9%97%AE%E9%A2%98)。
> 
> 刚回翻了下，看到了原有的类似问题，谢谢您

不客气，后续有其他问题和建议也欢迎提出。

**Comment by xiangzhanyou** [comment]
> > > 可以参考[如何解决Jackson兼容性问题](https://github.com/wechatpay-apiv3/wechatpay-apache-httpclient#%E5%A6%82%E4%BD%95%E8%A7%A3%E5%86%B3Jackson%E5%85%BC%E5%AE%B9%E6%80%A7%E9%97%AE%E9%A2%98)。
> > 
> > 
> > 刚回翻了下，看到了原有的类似问题，谢谢您
> 
> 不客气，后续有其他问题和建议也欢迎提出。

全乱套了，版本与原有的依赖冲突……

**Comment by lianup** [comment]
可以贴上具体的报错场景或者截图吗？

**Comment by xy-peng** [comment]
> 请问可以有什么其他的解决方案吗？

你们项目原有的 Jackson 依赖是多少？ 什么组件引入的？

在指定 Jackson 版本后报错的什么错？

**Comment by xiangzhanyou** [comment]
> > 请问可以有什么其他的解决方案吗？
> 
> 你们项目原有的 Jackson 依赖是多少？ 什么组件引入的？
> 
> 在指定 Jackson 版本后报错的什么错？

原有的项目依赖的Jackson版本为：2.9.9

现有SpringBoot版本为 2.1.8.RELEASE

指定Jackson版本后的error:
![image](https://user-images.githubusercontent.com/18008592/160797443-62279406-309d-4785-8594-62e0d5e4252b.png)

**Comment by xiangzhanyou** [comment]
![image](https://user-images.githubusercontent.com/18008592/160797515-2a4ea4e6-f28f-46ab-a101-a09a8ae26666.png)

**Comment by xy-peng** [comment]
抛出的是什么异常？能否发下最上层的 callstack frame ？

**Comment by xy-peng** [comment]
springboot 2.1.8 理论上应该可以直接升级 jackson 版本的，你也可以试试指定 2.11.4 看看。

**Comment by xiangzhanyou** [comment]
> 抛出的是什么异常？能否发下最上层的 callstack frame ？

Caused by: java.lang.IllegalStateException: Failed to introspect Class [com.fasterxml.jackson.databind.ObjectMapper] from ClassLoader [sun.misc.Launcher$AppClassLoader@18b4aac2]
	at org.springframework.util.ReflectionUtils.getDeclaredMethods(ReflectionUtils.java:507)
	at org.springframework.util.ReflectionUtils.doWithLocalMethods(ReflectionUtils.java:367)
	at org.springframework.beans.factory.annotation.InitDestroyAnnotationBeanPostProcessor.buildLifecycleMetadata(InitDestroyAnnotationBeanPostProcessor.java:207)
	at org.springframework.beans.factory.annotation.InitDestroyAnnotationBeanPostProcessor.findLifecycleMetadata(InitDestroyAnnotationBeanPostProcessor.java:189)
	at org.springframework.beans.factory.annotation.InitDestroyAnnotationBeanPostProcessor.postProcessMergedBeanDefinition(InitDestroyAnnotationBeanPostProcessor.java:128)
	at org.springframework.context.annotation.CommonAnnotationBeanPostProcessor.postProcessMergedBeanDefinition(CommonAnnotationBeanPostProcessor.java:297)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.applyMergedBeanDefinitionPostProcessors(AbstractAutowireCapableBeanFactory.java:1077)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.doCreateBean(AbstractAutowireCapableBeanFactory.java:567)
	... 93 common frames omitted
Caused by: java.lang.NoClassDefFoundError: com/fasterxml/jackson/core/StreamReadFeature
	at java.lang.Class.getDeclaredMethods0(Native Method)
	at java.lang.Class.privateGetDeclaredMethods(Class.java:2701)
	at java.lang.Class.getDeclaredMethods(Class.java:1975)
	at org.springframework.util.ReflectionUtils.getDeclaredMethods(ReflectionUtils.java:489)
	... 100 common frames omitted
Caused by: java.lang.ClassNotFoundException: com.fasterxml.jackson.core.StreamReadFeature
	at java.net.URLClassLoader.findClass(URLClassLoader.java:382)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:418)
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:355)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:351)
	... 104 common frames omitted

与目标 VM 断开连接, 地址为: ''127.0.0.1:55704'，传输: '套接字''

进程已结束,退出代码1

**Comment by xiangzhanyou** [comment]
> springboot 2.1.8 理论上应该可以直接升级 jackson 版本的，你也可以试试指定 2.11.4 看看。

切换依赖版本到2.11.4也是不行

**Comment by xiangzhanyou** [comment]
测试成功了，三个依赖同时指定版本：

 <dependency>
            <groupId>com.fasterxml.jackson.core</groupId>
            <artifactId>jackson-core</artifactId>
            <version>2.12.5</version>
        </dependency>
        <dependency>
            <groupId>com.fasterxml.jackson.core</groupId>
            <artifactId>jackson-annotations</artifactId>
            <version>2.12.5</version>
        </dependency>
        <dependency>
            <groupId>com.fasterxml.jackson.core</groupId>
            <artifactId>jackson-databind</artifactId>
            <version>2.12.5</version>
        </dependency>

**Comment by xy-peng** [comment]
感谢反馈，FAQ中遗漏了，我们补充下
