### ISSUE TITLE
密钥超过128位报错

### ISSUE THREAD

**Issue by chiangho** [wechatpay-apiv3/wechatpay-apache-httpclient#166]
ava.lang.IllegalArgumentException: java.security.InvalidKeyException: Illegal key size
        at com.wechat.pay.contrib.apache.httpclient.util.AesUtil.decryptToString(AesUtil.java:47) ~[wechatpay-apache-httpclient-0.4.7.jar!/:0.4.7]
        at com.wechat.pay.contrib.apache.httpclient.util.CertSerializeUtil.deserializeToCerts(CertSerializeUtil.java:42) ~[wechatpay-apache-httpclient-0.4.7.jar!/:0.4.7]
        at com.wechat.pay.contrib.apache.httpclient.cert.CertificatesManager.downloadAndUpdateCert(CertificatesManager.java:267) ~[wechatpay-apache-httpclient-0.4.7.jar!
        at com.wechat.pay.contrib.apache.httpclient.cert.CertificatesManager.initCertificates(CertificatesManager.java:295) ~[wechatpay-apache-httpclient-0.4.7.jar!/:0.4
        at com.wechat.pay.contrib.apache.httpclient.cert.CertificatesManager.putMerchant(CertificatesManager.java:152) ~[wechatpay-apache-httpclient-0.4.7.jar!/

**Comment by XingYu89757** [comment]
查看jdk使用版本

- 1.8_151之前的话需要下载JCE
- 1.8_151到1.8_171之间需要手动开启crypto.policy=unlimited
- 1.8_171之后默认是开启的，按道理不会出现这种情况

[[参考连接](https://www.oracle.com/java/technologies/javase/8all-relnotes.html#JDK-8153005)](https://www.oracle.com/java/technologies/javase/8all-relnotes.html#JDK-8153005)

> Unlimited cryptography enabled by default
> 
> The JDK uses the Java Cryptography Extension (JCE) Jurisdiction Policy files to configure cryptographic algorithm restrictions. Previously, the Policy files in the JDK placed limits on various algorithms. This release ships with both the limited and unlimited jurisdiction policy files, with unlimited being the default. The behavior can be controlled via the new 'crypto.policy' Security property found in the /lib/java.security file. Please refer to that file for more information on this property.
> 
> See [[JDK-8170157](http://bugs.java.com/view_bug.do?bug_id=JDK-8170157)](http://bugs.java.com/view_bug.do?bug_id=JDK-8170157)
