### ISSUE TITLE
java.lang.NoSuchMethodError: org.apache.http.client.methods.HttpRequestWrapper.getTarget()

### ISSUE THREAD

**Issue by 279832523** [wechatpay-apiv3/wechatpay-apache-httpclient#63]
java.lang.NoSuchMethodError: org.apache.http.client.methods.HttpRequestWrapper.getTarget()Lorg/apache/http/HttpHost;
	at com.wechat.pay.contrib.apache.httpclient.SignatureExec.execute(SignatureExec.java:48)
	at org.apache.http.impl.execchain.RetryExec.execute(RetryExec.java:85)
	at org.apache.http.impl.execchain.RedirectExec.execute(RedirectExec.java:108)
	at org.apache.http.impl.client.InternalHttpClient.doExecute(InternalHttpClient.java:186)
	at org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:82)
	at org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:106)

**Comment by xy-peng** [comment]
apache httpclient版本是？

根据[Apache HttpClient文档](https://www.javadoc.io/static/org.apache.httpcomponents/httpclient/4.5.7/org/apache/http/client/methods/HttpRequestWrapper.html#getTarget())，4.4+应该有对应的方法

**Comment by 279832523** [comment]
谢谢，更换httpclient版本解决问题，另外还出现InvalidKeyException: Illegal key size 的问题，尝试了网上教的替换US_export_policy.jar和local_policy.jar  或者修改java.security 配置，也还报错

**Comment by 279832523** [comment]
重装jdk解决了

**Comment by xy-peng** [comment]
[常见问题](https://wechatpay-api.gitbook.io/wechatpay-api-v3/chang-jian-wen-ti/api-v3-mi-yao-xiang-guan#shi-yong-java-jia-zai-mi-yao-shi-pao-chu-yi-chang-invalidkeyexception-illegal-key-size)有这个问题的具体说明的。
