### ISSUE TITLE
微信部分接口没有返回应答签名，导致验签失败

### ISSUE THREAD

**Issue by hyc125** [wechatpay-apiv3/wechatpay-apache-httpclient#95]
例如下载交易账单接口，没有返回签名，导致验签失败

能否设置一个HTTP请求头例如：IGNORE_WECHAT_RESPNOSE_SIGNATURE

当请求头有该字段时，`com.wechat.pay.contrib.apache.httpclient.SignatureExec#executeWithSignature`不进行验签操作

```
Caused by: org.apache.http.HttpException: 应答的微信支付签名验证失败
	at com.wechat.pay.contrib.apache.httpclient.SignatureExec.executeWithSignature(SignatureExec.java:80)
	at com.wechat.pay.contrib.apache.httpclient.SignatureExec.execute(SignatureExec.java:56)
	at org.apache.http.impl.execchain.RetryExec.execute(RetryExec.java:89)
	at org.apache.http.impl.execchain.RedirectExec.execute(RedirectExec.java:110)
	at org.apache.http.impl.client.InternalHttpClient.doExecute(InternalHttpClient.java:185)
```

**Comment by xy-peng** [comment]
> 能否设置一个HTTP请求头例如：IGNORE_WECHAT_RESPNOSE_SIGNATURE

不行，这样坏人伪造的请求带上这个头，岂不是可以“欺骗”你了？

你可以参考[如何下载平台证书](https://github.com/wechatpay-apiv3/wechatpay-apache-httpclient#%E5%A6%82%E4%BD%95%E4%B8%8B%E8%BD%BD%E5%B9%B3%E5%8F%B0%E8%AF%81%E4%B9%A6)，**仅为下载账单**起一个不验证签名的 Client。

```java
CloseableHttpClient httpClient = WechatPayHttpClientBuilder.create()
  .withMerchant(mchId, mchSerialNo, merchantPrivateKey)
  .withValidator(response -> true) // NOTE: 设置一个空的应答签名验证器，**不要**用在业务请求
  .build();
```
